# Generated by Django 5.0.6 on 2024-05-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carreto',
            name='estaActiu',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='carreto',
            name='pagat',
            field=models.BooleanField(default=False),
        ),
    ]
