# Generated by Django 5.0.6 on 2024-05-13 17:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comandes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagat', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('ordre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='comandes.ordre')),
            ],
        ),
    ]
